wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714661456.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.11.8
      5: 0.16.6
      6: 4.39.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 128
max_length:
  desc: null
  value: null
num_test_samples:
  desc: null
  value: 16
num_detector_samples:
  desc: null
  value: 16
model_name:
  desc: null
  value: openai-community/gpt2
dataset_size:
  desc: null
  value: 16
